### ISSUE TITLE
SetKeyboardFocusHere() Can't press button?

### ISSUE THREAD

**Issue by Majed93** [ocornut/imgui#134]
I'm using SetKeyboardFocusHere() function to set the focus on the text field, but once i do this i can't seem to click a button to go back to the main menu?

My code is like this 
ImGui::PushAllowKeyboardFocus(false);
				ImGui::SetKeyboardFocusHere();
				ImGui::InputText("", strPlain, IM_ARRAYSIZE(strPlain), ImGuiInputTextFlags_CallbackCharFilter, TextFilters::FilterAZ);
				ImGui::PopAllowKeyboardFocus();

Even without the push and pop parts it doesn't seem to work

**Comment by ocornut** [comment]
What do you mean by "click a button to go back to the main menu" ? More context would be useful.

If you call SetKeyboardFocusHere() the text field will always be in focus so you won't be able to focus another widget.

**Comment by Majed93** [comment]
I've got a button, a widget, which carries out a function.

How would i focus on the text field but be able to use other widgets at the same time?

**Comment by ocornut** [comment]
Well you can't have focus on two widgets simultaneously, this is a given in most user interfaces.
But I think I understand what you are expecting and I think I recent change with the active / hovering system made it harder to do (currently since about a month when a text input is active you can't click a button immediately, you have to click once to release focus and click again). 
You should be able to do:

    if (ImGui::IsAnyItemActive()) 
        ImGui::SetKeyboardFocusHere().

To take back unused focus but still allow to click a button, but right now with the issue described above I think it may not work. Give me a little time to look into it.

You would generally use SetKeyboardFocusHere() as an event (e.g. window appears, user clicked a button) rather than all the time. When you call SetKeyboardFocusHere() you essentially say "take away the focus from whichever widget may be using it - which can be the other button - and give it to that text field".

**Comment by ocornut** [comment]
So I have fixed a bug and you can click a button which a text input is active.
However if you use this:

```
if (!ImGui::IsAnyItemActive()) 
    ImGui::SetKeyboardFocusHere();
```

The text widget will lose its selection / cursor position everytime you click a button, which may be problematic. I'll see if I can work on a system to preserve selection which other widgets are activated.

**Comment by ocornut** [comment]
Some data are now persistent if you keep using the same InputText() - if you switch to another you'll lose the cursor position/selection, but you can click on a button while a InputText is active and when it'll come back focused by code the selection will be restored.

So using the block above should work for your use case.

It doesn't apply to using TAB to cycle through (always select all) neither CTRL+Click on a Input Text (also select all).

**Comment by kavika13** [comment]
Would an ImGuiSetCond be possible or make sense for this?

**Comment by Remist0** [comment]
Hello, Im using this code
`if (!ImGui::IsAnyItemActive())
		ImGui::SetKeyboardFocusHere();`
but it still not works with Combo's widgets. They still loosing focus after combo-window appears first time. How can I fix that?
